Aiven-Open/astacus

- .pylintrc
- astacus/coordinator/coordinator.py
- astacus/node/config.py
- astacus/node/download.py
- astacus/node/node.py
- astacus/node/snapshot.py
- astacus/node/snapshotter.py
- astacus/node/uploader.py
- examples/astacus-files-local.yaml
- tests/unit/coordinator/conftest.py
- tests/unit/node/conftest.py
- tests/unit/node/test_node_download.py
.. as seen from looking at logs in prod; nothing gamebreaking, although race conditions in done handling led to partial backups (rarely).
> Some minor fixes

- astacus/common/progress.py
- astacus/coordinator/api.py
- astacus/coordinator/coordinator.py
- astacus/coordinator/plugins/base.py
- tests/unit/common/test_progress.py
- tests/unit/coordinator/test_backup.py
- tests/unit/coordinator/test_restore.py
Collects and reports a combined progress value across all steps of backup and restore operations.
> coordinator: report progress from restore and backup operations

- astacus/server.py
Refactored the way in which the ASGI Sentry middleware is setup. This should also fix a bug in shutdown event handler.
> server: refactored asgi sentry middleware initalization

- .github/workflows/lint.yml
- .github/workflows/tests.yml
- .gitignore
- Dockerfile.fedora
- Dockerfile.ubuntu
- Makefile
- astacus.spec
- astacus/common/utils.py
- astacus/config.py
- astacus/node/snapshotter.py
- astacus/server.py
- requirements.testing.txt
- setup.cfg
- tests/system/conftest.py
- tests/system/test_astacus.py
- .gitignore: Added py.typed
- Fix some recent pylint complaints
- Update requirements and fix Dockerfiles to work better
- common: Bound SEEK_SET to within file size
- github: Python 3.9 by default
- snapshotter: Support src=dst mode
- tests: Added pytest-order dependency (systest(s?) run last)
- tests: Do not use astacus binary, instead python3 -m astacus.main
> Miscellaneous fixes (from mst-cassandra branch)

- astacus/client.py
- astacus/common/rohmustorage.py
- astacus/common/statsd.py
- astacus/config.py
- astacus/coordinator/coordinator.py
- astacus/coordinator/plugins/__init__.py
- astacus/coordinator/plugins/base.py
- astacus/coordinator/plugins/clickhouse/client.py
- astacus/coordinator/plugins/clickhouse/plugin.py
- astacus/coordinator/plugins/clickhouse/steps.py
- astacus/coordinator/plugins/m3db.py
- mypy.ini
- tests/integration/coordinator/plugins/clickhouse/conftest.py
- tests/integration/coordinator/plugins/clickhouse/test_plugin.py
- tests/unit/coordinator/plugins/clickhouse/test_config.py
- tests/unit/coordinator/plugins/test_m3db.py
- tests/unit/coordinator/test_restore.py
- Making mypy somewhat more stricter, and fixed some typing things that fell out of it.
- Fixed plugin loading to be lazy (so the Cassandra plugin can be really optional)
> mypy typing fixes + make plugins lazy-loaded

- astacus/common/ipc.py
- astacus/coordinator/plugins/cassandra/plugin.py
- astacus/coordinator/plugins/cassandra/restore_steps.py
- astacus/node/cassandra.py
- tests/unit/coordinator/plugins/cassandra/test_restore_steps.py
- tests/unit/node/test_node_cassandra.py
Details in the commit messages
> cassandra: some small restore improvements

- Dockerfile.fedora
- requirements.testing.txt
Updating to more recent packages
> misc: update Docker Fedora version to fc35, bump anyio and pre-commit versions

- astacus/common/ipc.py
- astacus/coordinator/list.py
- tests/unit/coordinator/conftest.py
- tests/unit/coordinator/test_list.py
Rebasing #93 on main meant this PR's changeset was lost, given it had #93 as base branch.
> Backup size calculation fix (has passed review)

- .pre-commit-config.yaml
See https://github.com/PyCQA/isort/pull/2078
> Update pre-commit to fix incompatible isort and poetry versions

- astacus/coordinator/plugins/clickhouse/plugin.py
- astacus/coordinator/plugins/clickhouse/steps.py
- tests/unit/coordinator/plugins/clickhouse/test_steps.py
> clickhouse: increase FREEZE and UNFREEZE timeout

- astacus/common/ipc.py
- astacus/node/api.py
- astacus/node/cassandra.py
- astacus/node/clear.py
- astacus/node/download.py
- astacus/node/node.py
- astacus/node/snapshot.py
- astacus/node/snapshotter.py
This is preparatory work for #116
Some changes related to `req` and `progress` are there to reduce the amount of `assert X is not None`.
>  node: add type hints 

- astacus/coordinator/plugins/m3db.py
This step needs to run before RewriteEtcdStep.
> m3db: fix MapNodesStep order

- tests/integration/coordinator/plugins/clickhouse/test_plugin.py
We only need to test that the table structure is restored correctly along with the rest of the schema metadata
[DDB-198]
> Test that the URL table engine is restored correctly

- .github/workflows/codeql-analysis.yml
Token permissions needed to be better specified
> Update CodeQL analysis GitHub Action

- astacus/node/download.py
The number of files to chown could be really large such that the argument list becomes to long.
> node: The chown_paths may be too large to chown

- README.md
Remove point about opensourcing from README, as it looks unnecessary.
> Remove mention about opensourcing

- astacus/coordinator/coordinator.py
- astacus/coordinator/plugins/base.py
- astacus/coordinator/plugins/cassandra/plugin.py
- astacus/coordinator/plugins/clickhouse/plugin.py
- astacus/coordinator/plugins/clickhouse/steps.py
- astacus/coordinator/plugins/files.py
- astacus/coordinator/plugins/flink/plugin.py
- astacus/coordinator/plugins/m3db.py
- tests/unit/coordinator/plugins/clickhouse/test_steps.py
See https://github.com/ClickHouse/ClickHouse/pull/52064
> clickhouse: account for FREEZE not replicated in v23.8

- astacus/coordinator/plugins/clickhouse/steps.py
- tests/unit/coordinator/plugins/clickhouse/test_steps.py
When listing all tables, we're only interested in the tables inside the Replicated database engine. In addition to that, we don't want ClickHouse to scan other database engines, some can be very slow to scan, like the ones querying remote databases (PostgreSQL, MySQL...).
ClickHouse is able to avoid scanning the tables of unwanted engines if
the query is simple enough for it to recognize which databases are
interesting. But the query we used did not allow that.
Split the query in two to ensure this is the case.
[DDB-777]
> clickhouse: fix slow list of tables

- pyproject.toml
Update dev dependencies to at least be the same or newer as it was previously before https://github.com/Aiven-Open/astacus/pull/194
> pyproject.toml: Update dev dependencies

- astacus/common/utils.py
httpx has a silly bug where it (very slowly) loads the ssl context even when it's not used at all.
We can work around that by disabling certificates verification when the protocol is HTTP.
A better fix would be to have a proper long-living scope for the client, but this requires large changes in astacus API implementation.
> fix very slow HTTP queries

- tests/integration/coordinator/plugins/clickhouse/test_plugin.py
There are no insert to sync after a restore. On the other hand, we need to sync after the manual inserts in the views and materialized views tests.
> tests: fix flaky inter-node select after insert
