Aiven-Open/astacus

astacus/common/op.py
astacus/common/utils.py
astacus/coordinator/coordinator.py
astacus/coordinator/plugins/base.py
tests/unit/common/test_op_stats.py
tests/unit/coordinator/test_backup.py
tests/unit/coordinator/test_lock.py

Collects the following metrics from running operations:
* `astacus_fail`, a counter reporting all failed operations, tagged with the op type
* `astacus_step_duration`, a timing stat for each step of an operation, tagged with op type and step name
* `astacus_lock_call_failure`,  a counter reporting locking failures, tagged with call (lock/unlock) and locker
* `astacus_op_running_for`, a gauge with seconds the op has run as value, tagged with op type and id

Add metrics

---

astacus/common/op.py
astacus/common/utils.py

The previous version was broken (CancelledError was caught in the blanket exception handling). Attempt to fix that + few things that spam sentry needlessly.

exception handling fixes

---

astacus/coordinator/api.py
astacus/coordinator/coordinator.py
astacus/coordinator/state.py

Otherwise, despite the caching, arbitrarily large memory usage may
occur if e.g. doing list request per second and it takes N seconds to
retrieve the manifests from object storage.

coordinator: Ensure only one list operation runs at a time

---

astacus/common/exceptions.py
astacus/common/ipc.py
astacus/common/op.py
astacus/common/rohmustorage.py
astacus/common/utils.py
astacus/coordinator/coordinator.py
astacus/coordinator/plugins/base.py
astacus/coordinator/plugins/m3db.py
astacus/coordinator/state.py
astacus/node/api.py
astacus/node/clear.py
astacus/node/download.py
astacus/node/node.py
astacus/node/snapshot.py
astacus/node/snapshotter.py
astacus/node/state.py
astacus/node/uploader.py
astacus/server.py
tests/unit/common/test_op_stats.py
tests/unit/common/test_utils.py
tests/unit/coordinator/plugins/test_m3db.py
tests/unit/coordinator/test_backup.py
tests/unit/coordinator/test_restore.py
tests/unit/node/test_node_download.py
tests/unit/node/test_node_snapshot.py

See commits for more details;
- astacus: Remove passing of SnapshotState in DownloadRequest
- coordinator: Add partial restore support
- coordinator: Add support for not doing anything if shutting down
- coordinator: request_from_nodes info instead of debug logging
- exceptions: Add RohmuException for 'got something wrong from rohmu'
- node: Handle FileExistsError in snapshot
- node: Add locking around use of Snapshotter
- utils: Removed use of too broad except in httpx_request

Partial restore support (+ fixes)

---

astacus/common/m3placement.py
astacus/coordinator/plugins/m3db.py
tests/unit/common/test_m3placement.py
tests/unit/coordinator/plugins/test_m3db.py

This is mainly so that we can use it from elsewhere, and the
functionality is relatively isolated. The code itself should be only
used from coordinator's m3db plugin within astacus codebase.

m3placement: Moved to own module under common

---

Makefile

Github Workflow builds started failing due to `apt-get install` failure for not found packages. Fixed by running `apt-get update` before install.

ci: fix installing ubuntu dependencies

---

astacus/common/rohmustorage.py
examples/astacus-files-google.json

Adds support for configuring rohmu storage with optional support for socks5 or http proxy connections. Rohmu supports proxying atm only for Google storage backend.

storage: proxy support for google storage backend

---

astacus/common/rohmustorage.py
setup.cfg
tests/unit/common/test_storage.py

Rohmu storage transfer object was created from a dict that does not take Pydantic model aliases into account. Included also a test to verify that the transfer object gets properly populated proxy config.

common: fix rohmu storage initialization

---

astacus/common/rohmustorage.py

The absence of these fields prevents from using pghoard's s3 driver with s3-compatible cloud storages.

models: add options to rohmu s3 storage model

---

astacus/common/ipc.py
astacus/coordinator/plugins/base.py
astacus/coordinator/plugins/clickhouse/parts.py
astacus/coordinator/plugins/clickhouse/steps.py

This value can be `null`/`None` when received from a node running the
code from before this change: https://github.com/aiven/astacus/commit/d92e18713b0284cceb62b6bdf0e5cb54ae80c75c
This only happened at the very beginning of a `SnapshotOp`,
when a node can return the value from `SnapshotOp.create_result()`
before the `state` is set in `SnapshotOp.snapshot()`.
This is a partial reversal, which allows the `None` value but stops
generating it.
After all nodes of a cluster are running code newer than the
previously mentioned commit, we will be able to remove the `Optional`
and all the asserts safely.

fix SnapshotResult.state backward compatibility

---

astacus/common/rohmustorage.py

Previous config only allowed for authentication via storage_account name and key, which provides access to all resources in a storage_account. This PR adjusts the schema validation for the config to allow for authentication via service principal (see [Azure docs](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/service-accounts-principal)). This approach provides granular permissions to be set at the container/blob levels. The service principal authentication itself is [being implemented in pghoard](https://github.com/aiven/pghoard/pull/509), which uses the config to build the AzureTransfer client to perform/restore backups.

common: add azure service principal auth support

---

astacus/coordinator/api.py
astacus/coordinator/coordinator.py

fastapi dependency injector runs all non-async injection functions in a separate thread, where the asyncio event loop is not available.
This breaks injection functions where we create async objects without using async/await.
A class constructor is a non-async function, we need to wrap it in an async function to avoid the fastapi thread:
Traceback (most recent call last):
File ".../uvicorn/protocols/http/h11_impl.py", line 384, in run_asgi
result = await app(self.scope, self.receive, self.send)
File ".../uvicorn/middleware/proxy_headers.py", line 45, in __call__
return await self.app(scope, receive, send)
File ".../fastapi/applications.py", line 146, in __call__
await super().__call__(scope, receive, send)
File ".../starlette/applications.py", line 102, in __call__
await …

coordinator: fix asyncio in sync dependency injectors

---

TODO.md
astacus.spec
astacus/common/rohmustorage.py
doc/design/implementation.md
requirements.testing.txt
setup.cfg
tests/unit/common/test_storage.py

Drop the pghoard dependency, depend only on the library itself.

rohmu: Replace pghoard.rohmu with rohmu library

---

.github/workflows/codeql-analysis.yml
.github/workflows/lint.yml
.github/workflows/tests.yml
.pylintrc
TODO.md
astacus/common/utils.py
astacus/node/download.py
mypy.ini
setup.cfg
setup.py
tests/unit/common/test_utils.py

- .pylintrc: Some tuning
- GHA tuning
- TODO: Reporting was fixed earlier
- common: Add open_path_with_atomic_rename to utils and use it in node download
- mypy.ini: Added h11 as ignored
- setup: Some requirements tuning
See commits for more details
made cassandra driver optional -> PRs should be much faster until we get cassandra really in

Miscellaneous fixes

---

astacus/common/rohmustorage.py

Add sas_token to credential schema as a replacement for Azure Service Principal credentials. The benefits of authenticating using a [SAS token](https://docs.microsoft.com/en-us/azure/storage/common/storage-sas-overview) are two-fold:
1. Simpler credential schema: `sas_token` string instead of `client_id`, `client_secret`, and `tenant_id` required for Service Principal authentication
2. Increased security (better access management): If a SAS token is compromised for any reason, the Shared Access Policy (SAP) it was created with can be deleted to immediately revoke access to the container. On the other hand, if Service Principal credentials are compromised, its credentials must be rotated and redistributed to any service that relied on the original credentials to continue performing backup …

common: use sas_token for azure auth

---

.pre-commit-config.yaml

This is blocking all other PRs since CI is broken.

Fix URL for flake8 pre-commit check and update hooks' versions

---

astacus/common/ipc.py
astacus/coordinator/list.py
tests/unit/coordinator/conftest.py
tests/unit/coordinator/test_list.py

When multiple nodes snapshot files with the same digest, the list operation sums their size incorrectly when returning the corresponding backup's size. 
Deduplicate the snapshot files by hexdigest, and retain the previous behaviour if the backup manifest has no associated snapshot state.

Fix backup size computation in the presence of duplicate snapshot files

---

tests/integration/coordinator/plugins/clickhouse/conftest.py
tests/unit/test_utils.py
tests/utils.py

Conftest ClickHouse version command output parsing fails for the latest official LTS build.

Fix clickhouse version CLI output parsing

---

.github/workflows/codeql-analysis.yml
.github/workflows/lint.yml
.github/workflows/tests-all.yml
.github/workflows/tests.yml
.pre-commit-config.yaml
.pylintrc
Dockerfile.ubuntu
Makefile
astacus/client.py
astacus/common/cassandra/schema.py
astacus/common/etcd.py
astacus/common/rohmustorage.py
astacus/common/statsd.py
astacus/common/utils.py
astacus/coordinator/coordinator.py
astacus/coordinator/plugins/base.py
astacus/coordinator/plugins/clickhouse/steps.py
astacus/server.py
requirements.testing.txt
setup.cfg
tests/unit/coordinator/plugins/clickhouse/test_parts.py
version_from_git.py

This PR is a maintenance update that aims at improving CI and updating requirements.
It streamlines build and test requirements, updates pre-commit hook versions, fixes the errors surfaced by pylint and mypy, and normalizes formatting for markdown and yaml according to a prettier pre-commit hook.
This is a follow up of #95 and prepares the field for an update to python 3.11.

Update linters and typing

---

.pylintrc
astacus/common/cassandra/schema.py
astacus/coordinator/plugins/cassandra/backup_steps.py
astacus/coordinator/plugins/cassandra/plugin.py
astacus/coordinator/plugins/cassandra/restore_steps.py
tests/unit/common/cassandra/conftest.py
tests/unit/common/cassandra/test_client.py
tests/unit/common/cassandra/test_restore_steps.py
tests/unit/common/cassandra/test_schema.py
tests/unit/coordinator/plugins/cassandra/builders.py
tests/unit/coordinator/plugins/cassandra/conftest.py
tests/unit/coordinator/plugins/cassandra/test_backup_steps.py
tests/unit/coordinator/plugins/cassandra/test_plugin.py
tests/unit/coordinator/plugins/cassandra/test_restore_steps.py
tests/utils.py

In a multi-datacenter setup, you might want to have separate Astacus
clusters in different datacenter, each managing it's own part of the
cluster (e.g. because your datacenters mirror each other and you want
independent backups in different regions for disaster recovery).
If you configure the datacenter parameter in Cassandra plugin config,
Astacus will ignore nodes from other datacenters when creating a
backup and rewrite the keyspace replication settings accordingly on
backup and restore (setting NetworkTopologyStrategy to replicate
within the datacenter you specified and allowing you to restore a
single region when other datacenters are not available).

cassandra: allow backup/restore of a single datacenter

---

astacus/common/op.py
astacus/common/progress.py
astacus/common/storage.py
astacus/common/utils.py
astacus/coordinator/cleanup.py
astacus/coordinator/cluster.py
astacus/coordinator/coordinator.py
astacus/coordinator/plugins/base.py
astacus/coordinator/plugins/m3db.py
astacus/node/clear.py
astacus/node/download.py
astacus/node/snapshot.py
astacus/node/snapshotter.py
astacus/node/uploader.py
astacus/server.py

Running astacus with a DEBUG log level is very verbose, mainly
because of the underlying libraries for object storage.
But running it with INFO loses a lot of useful information about
backup progress.
Raise the level of some of astacus log messages to make it
more useful to run at INFO level.
Also adjust the log formatting to be able to locate the logging sources.

Raise the level of some of the log messages

---

.flake8
.github/workflows/tests-all.yml
.pre-commit-config.yaml
.pylintrc
astacus/common/ipc.py
astacus/common/magic.py
astacus/common/rohmustorage.py
astacus/common/statsd.py
astacus/config.py
astacus/coordinator/api.py
astacus/node/api.py
requirements.testing.txt
setup.cfg
setup.py
tests/unit/common/test_statsd.py

This is a follow up of #93 focusing on test suite breakage ensuing the fastapi requirement update.

Update python to 3.11 and fix the test suite

---

astacus/coordinator/api.py
astacus/coordinator/coordinator.py
tests/unit/coordinator/test_busy.py
tests/unit/node/conftest.py

In order to avoid an excessive system load when using both Astacus and
Cashew, we'd like to understand when Astacus is actually doing something
(can happen if prune is restarted).

coordinator: expose busy concept

---

setup.py

I noticed this while trying to create a sanity check to build confidence that `importlib.metadata.distributions()` returns distributions in same order as used by import tooling. It looks like this typo in setup.py prevents the `tests` package from being excluded.
This can be verified like below, or by noting the presence of `tests/*` in `site-packages/astacus*egg-info/SOURCES.txt`.
```pycon
>>> [pkg for pkg, dists in importlib.metadata.packages_distributions().items() if "astacus" in dists]
['astacus', 'tests']
```
This could be prevented in the future by using a MANIFEST.in file in combination with running [check-manifest](https://github.com/mgedmin/check-manifest) in CI.

fix: Exclude tests from exposed modules

---

.pylintrc
astacus/coordinator/plugins/clickhouse/plugin.py
astacus/coordinator/plugins/clickhouse/steps.py
tests/integration/coordinator/plugins/clickhouse/conftest.py
tests/integration/coordinator/plugins/clickhouse/test_plugin.py
tests/integration/coordinator/plugins/clickhouse/test_steps.py
tests/unit/coordinator/plugins/clickhouse/test_steps.py

To clean up failed backups, each node is currently requested to remove leftover
snapshots from its shadow directories. Allow executing the ``SYSTEM UNFREEZE``
command that deletes frozen backup files from all disks at once. The command is 
run concurrently on all nodes.

Add option to remove leftover ClickHouse snapshots from disks

---

version_from_git.py

This no longer works as short_ver is not present, and SHORT_VER is a
shell command to get the version from git, which we already know doesn't
work.

version_from_git: fix version handling when not in git repo

---

.github/workflows/lint.yml
.github/workflows/tests-all.yml
.github/workflows/tests.yml
astacus/common/ipc.py
astacus/coordinator/plugins/base.py
astacus/coordinator/plugins/clickhouse/config.py
astacus/coordinator/plugins/clickhouse/disks.py
astacus/coordinator/plugins/clickhouse/manifest.py
astacus/coordinator/plugins/clickhouse/parts.py
astacus/coordinator/plugins/clickhouse/plugin.py
astacus/coordinator/plugins/clickhouse/replication.py
astacus/coordinator/plugins/clickhouse/steps.py
astacus/coordinator/plugins/zookeeper.py
mypy.ini
setup.py
tests/integration/conftest.py
tests/integration/coordinator/plugins/clickhouse/conftest.py
tests/integration/coordinator/plugins/clickhouse/test_plugin.py
tests/integration/coordinator/plugins/clickhouse/test_replication.py
tests/integration/coordinator/plugins/clickhouse/test_steps.py
tests/unit/coordinator/plugins/clickhouse/test_disks.py
tests/unit/coordinator/plugins/clickhouse/test_manifest.py
tests/unit/coordinator/plugins/clickhouse/test_parts.py
tests/unit/coordinator/plugins/clickhouse/test_replication.py
tests/unit/coordinator/plugins/clickhouse/test_steps.py
tests/unit/coordinator/plugins/test_zookeeper.py
tox.ini

The first thing is to support the disk prefix at the beginning of the file
path (anything before the store or shadow folder).
Some disks have metadata files instead of actual files in their store
folder, like object storage disks.
Even when the content is the same between replicas, the file
in object storage can be different, which makes the metadata files
different.
Because of that, we can't distribute parts among replicas and
we can't use a replicated ATTACH to exchange the data.
Even if we did, that wouldn't work great with all replication modes that
can be used in ClickHouse.
To fix that, stop doing parts distribution entirely and download all
parts from all nodes. To avoid the replication induced by ATTACH, replace
that with a SYSTEM RECOVER REPLICA: we remove the information in …

 clickhouse: add support for multiple and remote disks 

---

astacus.spec

We need snappy as a transitive dependency for rohmu; it was missing in
Fedora build-dep.

specfile: add snappy dependency

---

astacus/common/ipc.py
astacus/common/magic.py
astacus/common/snapshot.py
astacus/coordinator/plugins/base.py
astacus/coordinator/plugins/cassandra/plugin.py
astacus/coordinator/plugins/clickhouse/config.py
astacus/coordinator/plugins/clickhouse/disks.py
astacus/coordinator/plugins/clickhouse/file_metadata.py
astacus/coordinator/plugins/clickhouse/manifest.py
astacus/coordinator/plugins/clickhouse/plugin.py
astacus/coordinator/plugins/clickhouse/steps.py
astacus/coordinator/plugins/files.py
astacus/coordinator/plugins/m3db.py
astacus/node/api.py
astacus/node/clear.py
astacus/node/download.py
astacus/node/node.py
astacus/node/snapshot.py
astacus/node/snapshotter.py
tests/integration/coordinator/plugins/clickhouse/test_file_metadata.py
tests/system/test_astacus.py
tests/unit/coordinator/plugins/clickhouse/test_disks.py
tests/unit/coordinator/plugins/clickhouse/test_manifest.py
tests/unit/coordinator/plugins/clickhouse/test_steps.py
tests/unit/node/conftest.py
tests/unit/node/test_node_download.py
tests/unit/node/test_node_snapshot.py

After collecting metadata files of files in object storage, extract
the path of the remote files.
This required an extension of the snapshot protocol to have
different option for each glob.

clickhouse: extract the path of remote files 

---

astacus/common/storage.py
astacus/coordinator/api.py
astacus/coordinator/cleanup.py
astacus/coordinator/plugins/base.py
astacus/coordinator/plugins/clickhouse/async_object_storage.py
astacus/coordinator/plugins/clickhouse/config.py
astacus/coordinator/plugins/clickhouse/disks.py
astacus/coordinator/plugins/clickhouse/manifest.py
astacus/coordinator/plugins/clickhouse/plugin.py
astacus/coordinator/plugins/clickhouse/steps.py
tests/integration/coordinator/plugins/clickhouse/conftest.py
tests/integration/coordinator/plugins/clickhouse/test_plugin.py
tests/unit/coordinator/plugins/clickhouse/test_disks.py
tests/unit/coordinator/plugins/clickhouse/test_steps.py
tests/unit/coordinator/plugins/test_base.py
tests/unit/coordinator/test_cleanup.py
tests/unit/json_storage.py

Files in object storage that are older than the start time of the
newest backup and not part of any backup are now removed
during the cleanup operation.
If there are no backup, there are no files older than the newest
backup, so we do nothing.
[DDB-213]
[DDB-213]: https://aiven.atlassian.net/browse/DDB-213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

clickhouse: garbage collect object storage files

---

astacus/common/utils.py
astacus/node/config.py
astacus/node/download.py
tests/unit/common/test_utils.py

The goal is to be able to user a restored data dir when astacus and the restored service run
with a different user (but a shared group).
The first part is restoring less restricting file modes that are injected by `NamedTemporaryFile`
to enable read/write by the group on restored files.
The second part is more painful: despite having access to the restored files through the group
permission, some services also do file operations that require being the exact owner of the file.
This requires chowning the file, which cannot be done by the astacus or the service user.
This is solved by using sudo for the chown, and giving the sudo command a recognizable and
restricted shape that is suitable for sudoers directives.

node: handle mode and owner of downloaded files

---

astacus/common/rohmustorage.py
setup.cfg
tests/integration/coordinator/plugins/clickhouse/conftest.py

The incomplete models and type mismatch were causing integration failures with the latest rohmu.

deps: update rohmu models for the latest version

---

.github/workflows/lint.yml
astacus/coordinator/plugins/clickhouse/config.py
astacus/coordinator/plugins/zookeeper.py
astacus/coordinator/plugins/zookeeper_config.py
tests/integration/coordinator/plugins/clickhouse/test_zookeeper.py
tests/unit/coordinator/plugins/clickhouse/test_config.py

Kazoo supports digest authentication and clients may want to authenticate their requests. Implement it for the ClickHouse plugin.

zookeeper: add support for client authentication

---

astacus/common/ipc.py
astacus/coordinator/plugins/base.py
astacus/coordinator/plugins/cassandra/plugin.py
astacus/coordinator/plugins/cassandra/restore_steps.py
astacus/coordinator/plugins/clickhouse/plugin.py
astacus/coordinator/plugins/files.py
astacus/coordinator/plugins/m3db.py
astacus/node/cassandra.py
tests/unit/coordinator/plugins/cassandra/test_plugin.py
tests/unit/coordinator/plugins/cassandra/test_restore_steps.py
tests/unit/coordinator/plugins/test_m3db.py

Base it upon the node replacement for dead nodes (replace_address), but
skip the streaming stage, since we're downloading the data from object
storage. This is not production-ready yet, because the current process
loses all the writes since the last backup when restoring. Incremental
backup and restore to be introduced later.
After downloading the snapshot, stop Cassandra on the node we took the
snapshot of. That node might no longer be in the cluster, we attempt
to match it to configuration nodes the same way we match configuration
nodes to live cluster nodes when creating the backup.
Then start the replacement node with replace_address and
skip_bootstrap_streaming parameters. Wait until it is up, at this point
Cassandra should remove the old node from gossip because we instructed
it to …

Implement basic partial restore for Cassandra

---

tests/unit/test_client.py

Test the success case and outcome.
Test that the timeouts honour the global wait_completion.

Add more test for reload config behavior

---

astacus/node/snapshotter.py
tests/unit/node/test_snapshotter.py

When using the `src==dst` mode of the snapshotter, the `relative_path_to_snapshotfile` mutable member keeps remembering files that don't exist anymore.
This variable is read after the snapshot and then used to select which files to upload. Since these files don't exist anymore, they can't be uploaded and the backup fails.

Fix snapshotter not forgetting removed files

---

astacus/common/ipc.py
astacus/coordinator/plugins/cassandra/plugin.py
astacus/node/api.py
astacus/node/cassandra.py
astacus/node/config.py
tests/unit/node/test_node_cassandra.py

To avoid restore retries to fail in a loop, because the previous attempt left something in the data directory, stop Cassandra and clean the data directory before attempting restoration. To avoid accidentally deleting live node data, blacklist potentially damaging restore operations by default. Blacklist should be explicitly reset when configuring a node to perform restoration.

Bring Cassandra to a known state before restoring

---

astacus/coordinator/plugins/clickhouse/async_object_storage.py
astacus/coordinator/plugins/clickhouse/disks.py
astacus/coordinator/plugins/clickhouse/parts.py
astacus/coordinator/plugins/clickhouse/plugin.py
astacus/coordinator/plugins/clickhouse/steps.py
requirements.testing.txt
setup.cfg
tests/integration/coordinator/plugins/clickhouse/conftest.py
tests/integration/coordinator/plugins/clickhouse/test_plugin.py
tests/unit/coordinator/plugins/clickhouse/test_client.py
tests/unit/coordinator/plugins/clickhouse/test_disks.py
tests/unit/coordinator/plugins/clickhouse/test_parts.py
tests/unit/coordinator/plugins/clickhouse/test_steps.py

When restoring from an object storage that is different from the default one,
copy files from the restoring storage config to the default storage config.
This adds support for restoring tables using object storage files
as well as tables using local storage.
This relies on an unmerged version of romhu to allow copying files
between buckets.

clickhouse: copy object storage files on restore

---

astacus/common/rohmustorage.py
astacus/common/storage.py
astacus/node/uploader.py

Instead of encrypting and compressing the entire file on disk and then uploading that.
Progressively compress, encrypt and upload at the same time.
This reduces the Disk IO load during backups and avoid filling the disk if there is not enough
space left and individual files are large (such as Cassandra SSTable or ClickHouse part files).
[DDB-543]

common: stream uploaded files

---

astacus/common/cassandra/client.py

Logging full stack trace when we fail to connect to the local Cassandra instance seems overkill, because it's a transient error -> it's retried and the stack traces clutter the log. Also is picked up by Sentry SDK, which is unnecessary since the exception is expected.

Log only the error when connecting to Cassandra

---

astacus/client.py
astacus/common/magic.py
astacus/coordinator/api.py
astacus/coordinator/coordinator.py
astacus/coordinator/list.py
astacus/coordinator/plugins/base.py
astacus/coordinator/plugins/cassandra/plugin.py
astacus/coordinator/plugins/clickhouse/plugin.py
astacus/coordinator/plugins/files.py
astacus/coordinator/plugins/flink/plugin.py
astacus/coordinator/plugins/m3db.py
astacus/node/api.py
astacus/node/clear.py
astacus/node/config.py
astacus/node/download.py
astacus/node/node.py
astacus/node/snapshot.py
tests/unit/coordinator/plugins/test_base.py

Add the concept of a lighter "delta" backup to Astacus. Lighter "delta" backups contain only the data reported as such by the database itself (e.g. via commit logs or Cassandra incremental backups). Compared to the "regular" snapshot-based backups, delta backups:
* do not require listing the hexdigest storage to create the backup
* do not require to build a full list of files present in the database to determine the diff
* can be restored one on top of the other (during node replacement this allows to do "catch-up" on the replacement before draining&removing the old node, decreasing the window of time the cluster is running with RF-1 nodes)
The delta APIs re-use the download and snapshot methods already present, but:
* deltas are gathered and uploaded using a different Snapshotter …

Implement delta backups for Cassandra, part 1

---

astacus/common/cassandra/config.py
astacus/common/cassandra/utils.py
astacus/common/ipc.py
astacus/coordinator/plugins/cassandra/plugin.py
astacus/node/api.py
astacus/node/cassandra.py
tests/unit/conftest.py
tests/unit/node/test_node_cassandra.py

Instead of hard-coding sstable restoration glob and matching strategy, make it configurable from coordinator side. Allows to keep the subop enum small while allowing to add incremental backup restoration.
Presently we use 2 configurations:
* restore without system_schema, match tables by name
* restore with system_schema, match tables by id
Incremental backup restoration needs both these options, but with a different table glob (from /backups instead of /snapshots/astacus).

Make sstable restoration configurable

---

astacus/common/ipc.py
astacus/coordinator/cluster.py
astacus/coordinator/plugins/base.py
astacus/coordinator/plugins/cassandra/plugin.py
astacus/node/api.py
astacus/node/snapshot.py
astacus/node/snapshotter.py
tests/unit/coordinator/plugins/test_base.py
tests/unit/node/test_snapshotter.py

Allow the coordinator to release the files that were uploaded during backup creation. Helps to free disk space after the backup was uploaded. Especially useful for Cassandra, since because of compactions we end up keeping around copies of old sstables.

Release extra files in dst after upload

---

.pre-commit-config.yaml
Makefile
astacus/common/cassandra/schema.py
astacus/coordinator/plugins/clickhouse/steps.py
tests/integration/conftest.py
tests/integration/coordinator/plugins/clickhouse/conftest.py
tests/integration/coordinator/plugins/clickhouse/test_client.py
tests/integration/coordinator/plugins/clickhouse/test_plugin.py
tests/integration/coordinator/plugins/clickhouse/test_steps.py
tests/integration/coordinator/plugins/flink/test_steps.py
tests/system/conftest.py
tests/system/test_config_reload.py
tests/unit/common/cassandra/test_client.py
tests/unit/common/test_op.py
tests/unit/common/test_storage.py
tests/unit/coordinator/plugins/cassandra/test_backup_steps.py
tests/unit/coordinator/plugins/cassandra/test_plugin.py
tests/unit/coordinator/plugins/clickhouse/test_config.py
tests/unit/coordinator/plugins/clickhouse/test_steps.py
tests/unit/coordinator/plugins/test_base.py
tests/unit/coordinator/test_backup.py
tests/unit/coordinator/test_list.py
tests/unit/coordinator/test_restore.py
tests/unit/node/conftest.py
tests/unit/node/test_node_cassandra.py
tests/unit/node/test_node_download.py
tests/unit/test_client.py
tests/utils.py

You can still opt out of type checking by not typing a function.  But if types are specified, we should check that they are correct (according to mypy).  This makes it easier to run mypy on new code in `tests` to check that it is correct without having a lot of preexisting errors appear.

tests: add type checking and fix type bugs

---

astacus/common/progress.py
astacus/node/api.py
astacus/node/clear.py
astacus/node/config.py
astacus/node/download.py
astacus/node/memory_snapshot.py
astacus/node/node.py
astacus/node/snapshot.py
astacus/node/snapshot_op.py
astacus/node/snapshotter.py
astacus/node/sqlite_snapshot.py
astacus/node/uploader.py
tests/system/conftest.py
tests/system/test_astacus.py
tests/unit/node/conftest.py
tests/unit/node/test_node_download.py
tests/unit/node/test_node_snapshot.py
tests/unit/node/test_snapshotter.py

DO NOT MERGE still testing with aiven-core.
Astacus can currently take up reasonable amount of ram if there are many files, especially when performing a snapshot.  This can eat into available ram for the database itself.
Split `Snapshotter` into 2 classes.  `Snapshot` responsible for holding all the data about a snapshot on disk, and `Snapshotter`, responsible for updating the snapshot to the current state.
Makes these classes generic and with 2 implementations, one holding all files in memory (equivalent to how Snapshotter currently works on master) and 1 with files stored on disk via SQLite.  The SQLite version uses constant memory and is not any slower in my benchmarks (in fact it may be a little faster).  You can look at this branch for benchmarks …

snapshotter: Use an SQLite backed snapshotter

---

astacus/common/cassandra/config.py
astacus/common/ipc.py
astacus/coordinator/plugins/base.py
astacus/coordinator/plugins/cassandra/plugin.py
astacus/coordinator/plugins/cassandra/restore_steps.py
astacus/coordinator/plugins/cassandra/utils.py
astacus/node/api.py
astacus/node/cassandra.py
tests/unit/conftest.py
tests/unit/coordinator/plugins/cassandra/test_restore_steps.py
tests/unit/coordinator/plugins/test_base.py
tests/unit/node/test_node_cassandra.py

When doing a partial restore, apply all the incremental changes we've
uploaded when creating delta backups. After restoring the snapshot,
download and put sstables from incremental backups into Cassandra's data
directory.

Restore delta backups in Cassandra

---

astacus/node/node.py

Different snapshots should be independent from each other, there's no value in isolating them programmatically by e.g. using different tables.

Put delta sqlite snapshot in a separate db

---

astacus/coordinator/plugins/base.py

The endgame we really want is adding per-node manifests and some sort of summary manifest to be handled here, not keeping the 'too old' manifests in memory helps a lot in case of nodes which have already taken too many backups.
With this, we will load only up to the <amount kept+1> manifests to memory at most, so having e.g. 70 manifests in object storage and 5 kept means we at most have 6 in memory at a time.
(As seen in production.)

coordinator: Make cleanup keep only interesting manifests

---

Makefile
pyproject.toml
requirements.testing.txt
tests/integration/coordinator/plugins/clickhouse/conftest.py
tests/system/conftest.py
tests/utils.py

This slows invoked subprocesses by ~30% (or less, if they do heavy computation) which is hopefully acceptable cost. We already did gather coverage on the main pytest process.
I wonder if this breaks codecov or if it is somehow broken anyway - https://app.codecov.io/gh/Aiven-Open/astacus/pull/165 shows this as in 'processing' state for half an hour now. Perhaps we're not classified as open source plan and are hitting some limit? Or different coverage invocation makes it unable to find the parent commit (it has coverage % which is higher than what is in `main`).

tests: Add combined coverage handling

---

astacus/coordinator/plugins/base.py
astacus/coordinator/plugins/cassandra/plugin.py
astacus/coordinator/plugins/clickhouse/plugin.py
astacus/coordinator/plugins/clickhouse/steps.py
tests/unit/coordinator/plugins/clickhouse/test_steps.py
tests/unit/coordinator/plugins/test_base.py

Minimal fix for large memory usage during cleanup.  Rather than store all manifests in memory, reread them one at a time.

cleanup: reduce memory usage

---

astacus/common/access_log.py
astacus/server.py
tests/unit/common/test_access_log.py

`POST` and `PUT` calls are much more interesting than `GET` calls, at  least from the point of view of the server.
Log `GET` requests at the `DEBUG` level while logging other methods at the `INFO` level.

lower log level of GET calls to DEBUG

---

astacus/server.py

The previous configuration was checking the level at the logger step bot not at the handler step, so logs were not filtered according to their modified log level.

filter access logs by levels

---

astacus/common/ipc.py
astacus/common/json_view.py
astacus/coordinator/list.py
astacus/coordinator/plugins/clickhouse/async_object_storage.py
astacus/coordinator/plugins/clickhouse/disks.py
astacus/coordinator/plugins/clickhouse/file_metadata.py
astacus/coordinator/plugins/clickhouse/manifest.py
astacus/coordinator/plugins/clickhouse/steps.py
astacus/node/download.py
astacus/node/snapshot.py
astacus/node/snapshot_groups.py
astacus/node/snapshotter.py
astacus/node/sqlite_snapshot.py
tests/integration/coordinator/plugins/clickhouse/test_file_metadata.py
tests/unit/common/test_json_view.py
tests/unit/coordinator/plugins/clickhouse/test_disks.py
tests/unit/coordinator/plugins/clickhouse/test_parts.py
tests/unit/coordinator/plugins/clickhouse/test_steps.py
tests/unit/coordinator/test_list.py
tests/unit/coordinator/test_restore.py
tests/unit/node/conftest.py
tests/unit/node/test_node_download.py
tests/unit/node/test_node_snapshot.py
tests/unit/node/test_snapshot_groups.py
tests/unit/node/test_snapshotter.py

This is not the optimal solution (splitting files, changing the manifest format, etc.)
But profiling shows significant reduction in memory usage for large manifests with these changes, without breaking backward compatibility:
- use `str` instead of `Path` wherever possible. The `Path` API is nice, but  the abstraction is too expensive when we have a large number of objects.
- only convert to `pydantic` models the subset of data that we care about, for instance if we want a single snapshot in an entire manifest, don't convert the entire manifest, just the single snapshot.
- `list_backups`: stay completely in json-land, but with type-safe accessors to read the data.
Tested on a large 800MiB manifest, peak usage during `list_backups` was reduced from ~8GiB to ~4.1GiB and lasted for a much …

reduce astacus memory usage [DDB-853]

---

astacus/coordinator/plugins/cassandra/plugin.py
astacus/coordinator/plugins/cassandra/restore_steps.py
astacus/coordinator/plugins/cassandra/utils.py
tests/unit/coordinator/plugins/cassandra/conftest.py
tests/unit/coordinator/plugins/cassandra/test_restore_steps.py
tests/unit/coordinator/plugins/cassandra/test_utils.py

cassandra is going to try and contact these stopped nodes to get hashes
from them, but that is bound to fail as the cassandra there has been
stopped. This only delays the whole restore step and causes un-necessary
timouts and various places.

cassandra: drop nodes from cluster when they are stopped

---

astacus/coordinator/plugins/clickhouse/plugin.py

This step can be very slow with pathological table structures.
[DDB-889]

clickhouse: bump default restore_replica_timeout to 3600sec

---

Dockerfile.fedora
astacus/common/rohmustorage.py
astacus/common/utils.py
setup.cfg
tests/unit/common/test_utils.py

rohmu: speedup file decryption
Improve backup restoration speed by removing unnecessary operations.
Remove unnecessary operations for each file download:
1. second retrival of key metadata
2. RSA private key loading, which requires compute-intensive checks
For workload with many small files it results to a large speedup.
[DDB-885]

Khatskevich speedup backup restoration [DDB-855]

---

astacus/coordinator/plugins/clickhouse/steps.py
tests/unit/coordinator/plugins/clickhouse/test_steps.py

Like other experimental settings, whether they should be allowed or not is decided somewhere else, but astacus should not unnecessary fail if they were allowed.
[DDB-500]

clickhouse: make restore work with annoy index

---

astacus/coordinator/plugins/clickhouse/dependencies.py
astacus/coordinator/plugins/clickhouse/engines.py
astacus/coordinator/plugins/clickhouse/steps.py
tests/integration/coordinator/plugins/clickhouse/conftest.py
tests/integration/coordinator/plugins/clickhouse/test_plugin.py
tests/unit/coordinator/plugins/clickhouse/test_dependencies.py
tests/unit/coordinator/plugins/clickhouse/test_steps.py

This pr enables the restoration of databases with materialized views when:
1. Source table was deleted before backup.
2. Source table was not backed up by Astacus.
This is achieved by using `ATTACH` instead of `CREATE`, which performs
fewer checks at the moment of creation.
Misc: add a test for basic views to make sure they are restored properly
in similar case.
[DDB-890]

Properly support materialized views restoration

---

mypy.ini
pyproject.toml

Ignore uvicorn typing errors for the time being, and improve pyproject.toml dependencies when running mypy outside the pre-commit venv.

Pin mypy to version 1.8.0

---

tests/unit/common/cassandra/test_client.py

Fixes: 
```
AttributeError: 'called_with' is not a valid assertion. Use a spec for the mock if 'called_with' is meant to be an attribute.
``` 
on python 3.12.

tests: fix assertion

---

tests/integration/coordinator/plugins/clickhouse/test_plugin.py

These tests are flakey and need to be fixed.  Skipping until we fix issues with SYSTEM RESTORE REPLICA since for aiven-core this package cannot be built.

tests: skip clickhouse plugin tests

---

astacus/coordinator/plugins/clickhouse/plugin.py
astacus/coordinator/plugins/clickhouse/steps.py
tests/integration/coordinator/plugins/clickhouse/test_plugin.py

This prevents a race condition in the tests (but also in prod) where Astacus exits claiming a restore has happened but instead there are still parts being synced.

clickhouse: sync parts after system restore replica

---

astacus/common/utils.py

When using urllib3<=1.26.18 with uvicorn<=0.23.2 and python>=3.12, the socket shutdown method of urllib3 combines with the uvicorn server shutdown to leave the server stuck for many seconds:
https://github.com/encode/uvicorn/pull/2145
Updating urllib3 or uvicorn (or downgrading Python) fixes the bug, but Fedora 39 shipped Python 3.12 with old urllib3 and uvicorn.
Since we (sadly) open a connection just for a single request every time, we can disable the HTTP keep-alive. This allows the server to close the connection earlier, without waiting for the client.
This fixes the failing tests/system/test_astacus.py::test_astacus on Fedora 39.

Fix dangling socket causing uvicorn shutdown failure

---

.pre-commit-config.yaml
Makefile
astacus/common/progress.py
astacus/common/rohmustorage.py
astacus/common/snapshot.py
astacus/common/storage.py
astacus/common/utils.py
astacus/coordinator/plugins/base.py
astacus/coordinator/plugins/clickhouse/config.py
astacus/coordinator/plugins/zookeeper.py
astacus/node/download.py
astacus/node/snapshot_groups.py
astacus/node/sqlite_snapshot.py
mypy.ini
pyproject.toml
tests/integration/coordinator/plugins/clickhouse/conftest.py
tests/system/conftest.py
tests/unit/common/test_storage.py
tests/unit/common/test_utils.py
tests/unit/coordinator/test_list.py
tests/unit/node/test_node_cassandra.py
tests/unit/node/test_node_download.py
tests/unit/storage.py
tests/utils.py

The local hook allows specifying the dependencies only once, in the `pyproject.toml` file.
This ensures they're the same at development and CI times.
Typing file helper functions and Rohmu storage methods requires changing some parameter types to use `IO[bytes]` and `FileLike`. 
These allow pass both `BinaryIO` and `_TemporaryFileWrapper[bytes]` types to the functions.
Some type errors were ignored, notably to work around Pydantic quirks (parsing of enum value, models using a discriminator field to provide union typing).

Transition to using a local hook for type checking and fix surfaced type errors

---

.github/workflows/test.yml
pyproject.toml

Unpin uvicorn to avoid compatibility issues when installing other things.
Also add optional pinned versions: running `pip install -e .[f38]` or `f39`
(or combined  with `dev`) to get the same package versions as each Fedora version,
which helps when testing/debugging. It's also a useful reference table.
This is far from ideal, pip's version.txt would have been a better fit, but it's better than nothing.
We might want to do the same for dev dependencies if that proves to be useful.
Also repair the missing cassandra dependency (this was causing cassandra tests to not run).

unpin uvicorn and add optional pins

---

.github/workflows/test.yml
Makefile
pyproject.toml

It is not sufficient to exercise astacus with multiple python versions, as it is primarily used in a fedora environment with specific python packages.
Modify the CI test matrix to exercise certain fedora version python configurations, along with the correct python version which is packaged with these fedora versions.
This will help identify problems ahead of time, and better allow any issues to be addressed here, rather than via downstream patches.

Test multiple fedora configurations

---

pyproject.toml
tests/conftest.py
tests/integration/conftest.py
tests/plugins/__init__.py
tests/plugins/asyncio_loop.py

More recent pytest-asyncio loop do no support fixtures with non-function scopes, use our own version of the loop fixtures that fixes this problem.
This alternative version was used successfully for a few years in other repositories.

replace pytest-asyncio with asyncio_loop

---

.pre-commit-config.yaml

This avoids duplicated warning messages.

run mypy serially

---

.github/workflows/test.yml
.pre-commit-config.yaml
astacus/coordinator/plugins/clickhouse/dependencies.py
pyproject.toml

Extracted from https://github.com/Aiven-Open/astacus/pull/219 
Fixing the bug that disabled tests covered a few issues with them:
- flake8 was failing, this is covered by the "improve linting" commit.
- pylint was failing on f39/py3.12 deps, because pylint was still pinned to an old f38 version, bumping for both test runs it is not ideal, but #219 will provide a proper solution for that issue. Until then, it's better to run tests and have a more modern pylint than what f38 offers than not run tests at all.

Fix regression causing tests to not be run in GHA

---

.github/workflows/test.yml
astacus/node/sqlite_snapshot.py

With python 3.12 and 3.13 fetch results from SQLite3 in multi-threading applications are not consistent.
This causes an sqlite3.InterfaceError with "bad parameter or other API misuse"
Current solution is to set the cached_statement to 0.

disable sqlite cached statements

---

astacus/coordinator/plugins/clickhouse/config.py
astacus/coordinator/plugins/clickhouse/disks.py
astacus/coordinator/plugins/clickhouse/object_storage.py
astacus/coordinator/plugins/clickhouse/plugin.py
astacus/coordinator/plugins/clickhouse/steps.py
tests/unit/coordinator/plugins/clickhouse/test_steps.py

The `copy_files_from` method is not supported between different cloud providers. Add a very simple download/upload implementation of copying between different clouds in case we need to, make it configurable, since the operator configuring Astacus is likely to know whether direct in-cloud copying is possible with the credentials/configuration they provided.

clickhouse: add local copy strategy for cross-provider tiered storage restore

---

astacus/coordinator/plugins/clickhouse/object_storage.py

Rohmu download functions do not promise that the temporary file will be immediately readable after get_contents_to_fileobj exits. Seek it to the beginning of the temporary file before reading and uploading.

seek the temp file when copying between storages

---

astacus/coordinator/plugins/clickhouse/object_storage.py
astacus/coordinator/plugins/clickhouse/steps.py
pyproject.toml
tests/unit/coordinator/plugins/clickhouse/object_storage.py
tests/unit/coordinator/plugins/clickhouse/test_steps.py

Track the progress on the remaining object storage files that needs to be copied during `RestoreObjectStorageFilesStep`.
Expose as gauge `astacus_copy_tiered_object_storage_files_remaining_value`.
Syncing required with https://github.com/Aiven-Open/astacus/pull/228
Requires rohmu 2.7.0
- https://github.com/Aiven-Open/rohmu/pull/192

astacus: track remaining restored object files

---

astacus/coordinator/plugins/clickhouse/steps.py

This will always happen if there is no KeeperMap tables.

clickhouse: don't log error when keeper_map path does not exist

---

astacus/coordinator/plugins/clickhouse/steps.py
tests/integration/coordinator/plugins/clickhouse/test_plugin.py

If the table was dropped the table path still exists but the data ZNode is removed.  This leads to an error in backup.

clickhouse: account for dropped KeeperMap tables

---

astacus/main.py
astacus/manifest.py

Add a command-line tool that can be used to list/dump backup manifests in object storage without interacting with the server. Useful when debugging manifest compatibility issues/restoration bugs.
List example:
```
backup-2024-10-15T13:54:19+00:00
backup-2024-10-16T13:54:20+00:00
```
Describe example:
```
clickhouse manifest backup-2024-10-16T13:54:20+00:00
===============================
Started at: 2024-10-16T13:54:20.802652+00:00
Finished at: 2024-10-16T13:54:21.873076+00:00
Attempts: 1
Snapshot #0 created at 2024-10-16T13:54:20.875002+00:00 contains 11 files (25145965 bytes)
Node #0 uploaded 13605207 bytes out of 25145547
References 0 objects in tiered storage totalling 0 bytes
```
Dump example:
```
{
"start": "2024-10-16T13:54:20.802652Z",
"end": "2024-10-16T13:54:21.873076Z", …
```

Add a manifest introspection utility

---

tests/integration/coordinator/plugins/clickhouse/conftest.py
tests/integration/coordinator/plugins/clickhouse/test_plugin.py
tests/integration/coordinator/plugins/clickhouse/test_steps.py

The conditionals were valid for old setups. We can use named collections and ZooKeeper macro placeholders everywhere now.

Cleanup ClickHouse integration conftest

---

tests/integration/coordinator/plugins/clickhouse/conftest.py

* Set zero copy settings in tests.
* make sure object storage test table has data both on local and remote disk.

Zero copy tests

---

astacus/coordinator/coordinator.py
astacus/coordinator/plugins/base.py
astacus/coordinator/plugins/clickhouse/plugin.py
astacus/coordinator/plugins/clickhouse/steps.py
astacus/coordinator/plugins/zookeeper.py
tests/integration/coordinator/plugins/clickhouse/test_steps.py
tests/unit/coordinator/plugins/clickhouse/test_steps.py
tests/unit/coordinator/test_coordinator.py

The PR alters replicated users' privileges (through GRANT & REVOKE) during the backup. This ensures the KeeperMap tables' snapshot is consistent with the frozen table data.
[DDB-1237]

ClickHouse: pause KeeperMap insertion momentarily during backup

---

tests/system/conftest.py

The current `multiplier=1.3` setting leads to a timeout of 20s, which occurs frequently on slow CPUs.
Update the multipler to 1.4 which leads to a max timeout of ~85s. The change was tested by running the system test 30 times and ensuring the pipeline is green.

Increase system test backoff multiplier

---

astacus/coordinator/cluster.py

Raw and text data should be passed using ``content`` and not ``data``.

Fix httpx Request deprecation warning

---

astacus/coordinator/plugins/clickhouse/steps.py

For the read-only step, we're filtering by replicated users, whose grant information is stored in ZooKeeper.
This means that executing the query on multiple nodes is counterproductive. Instead of achieving faster information propagation, we're getting transaction errors from ZooKeeper. Any one of these can in turn fail the step.
Here's one such example:
```
Query failed: b'REVOKE INSERT, ALTER UPDATE, ALTER DELETE ON `default`.`keeper_map` FROM `alice`' on <host>:
status_code=500,
exception_code=999,
response=b'Code: 999. Coordination::Exception: Transaction failed: Op #0, path: /clickhouse/access/uuid/914a9caa-682f-5dce-4ed7-b0f16f564798. (KEEPER_EXCEPTION) (version 24.3.5.1)\n'
```

Only execute access rights change queries on a single node

---

astacus/coordinator/plugins/clickhouse/steps.py
astacus/manifest.py
tests/unit/coordinator/plugins/clickhouse/test_steps.py

Files can be uploaded _before_ a part appears in a backup manifest.
[DDB-1372]

clickhouse: Fix race condition in DeleteDanglingObjectStorageFilesStep

---

astacus/manifest.py

Usually you don't want to download files from all nodes in backup - for this you can just run the tool multiple times anyway.

Just download files from a single node in backup

---

astacus/coordinator/plugins/clickhouse/engines.py
tests/integration/coordinator/plugins/clickhouse/test_plugin.py

Test table creation with AzureBlobStorage

astacus: test azure blob storage table engine

---

astacus/coordinator/plugins/clickhouse/plugin.py
astacus/coordinator/plugins/clickhouse/steps.py
tests/integration/coordinator/plugins/clickhouse/test_steps.py
tests/unit/coordinator/plugins/clickhouse/test_steps.py

Emitting a "table is read-only" is more precise
and is already handled by Kafka Sink Connector
for ClickHouse.

Pause KeeperMap tables using read-only setting
